spring:
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  jwt:
    secret: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}

server:
  port: 8080

spring.config.import: optional:dotenv:.env, optional:application-prod.yml